export const languages = [
    { name: "English", code: "us" }, 
    { name: "Spanish", code: "es" }, 
    { name: "French", code: "fr" }, 
    { name: "German", code: "de" }, 
    { name: "Italian", code: "it" }, 
    { name: "Portuguese", code: "pt" }, 
    { name: "Russian", code: "ru" }, 
    { name: "Chinese (Simplified)", code: "cn" }, 
    { name: "Arabic", code: "ae" }, 
    { name: "Japanese", code: "jp" }, 
    { name: "Korean", code: "kr" }, 
    { name: "Hindi", code: "in" }, 
    { name: "Bengali", code: "bd" },
    { name: "Urdu", code: "pk" }, 
    { name: "Turkish", code: "tr" }, 
    { name: "Vietnamese", code: "vn" }, 
    { name: "Polish", code: "pl" }, 
    { name: "Dutch", code: "nl" }, 
    { name: "Swedish", code: "se" },
    { name: "Greek", code: "gr" }, 
    { name: "Thai", code: "th" }, 
    { name: "Indonesian", code: "id" }, 
    { name: "Romanian", code: "ro" }, 
    { name: "Czech", code: "cz" }, 
    { name: "Hungarian", code: "hu" }, 
    { name: "Danish", code: "dk" }, 
    { name: "Finnish", code: "fi" }, 
    { name: "Norwegian", code: "no" }, 
    { name: "Malay", code: "my" }, 
    { name: "Ukrainian", code: "ua" }, 
  ];
  